### ISSUE TITLE
Being able to add link to @mention manually

### ISSUE THREAD

**Issue by muan** [jekyll/jekyll-mentions#2]
Sometimes people don't have a GitHub profile, and I'd like to have [@benbalter](https://twitter.com/benbalter) instead of @benbalter. 

Looks like on .com it works as expected. However with `jekyll-mentions` I get:
[`<a href=‘https://github.com/benbalter’ class=‘user-mention’>@benbalter`](https://twitter.com/benbalter)

**Comment by parkr** [comment]
@muan This should be fixed now that we're using HTML Pipeline properly ✨ ❤️
