### ISSUE TITLE
Does not work with usernames starting with _

### ISSUE THREAD

**Issue by vallieres** [jekyll/jekyll-mentions#24]
I have this in one of my posts: @_davidsmith and it does not get picked up by the plugin.

**Comment by benbalter** [comment]
This is likely an upstream issue with HTML Pipeline, which we simply wrap. FWIW, it looks like @_davidsmith is not a valid GitHub username, as it doesn't render in comments here either.

**Comment by vallieres** [comment]
I should have mentioned that my setup is using Twitter as the social network. and http://twitter.com/_DavidSmith exists over there.
