### ISSUE TITLE
Feature: Link to twitter nicknames instead of github

### ISSUE THREAD

**Issue by wikimatze** [jekyll/jekyll-mentions#3]
Hi,

how about adding an option which enables you to set up the name domain for mentioning names in the `_config.yml` file?

**Comment by emma-sax4** [comment]
@marceloverdijk With the changes that are in the works here (https://github.com/jekyll/jekyll-mentions/pull/72), you'll be able to have a default base URL defined in the `_config.yml`, and then be able to define the base URL specifically for each file as well. With this, each file could have a different base URL!
