### ISSUE TITLE
Renders @something where it should not

### ISSUE THREAD

**Issue by vallieres** [jekyll/jekyll-mentions#30]
Hello,

Just realized that it also runs on my JSON-LD definition:

```
  <body class="">
      <script type="application/ld+json">
        {
             "<a href="https://github.com/context" class="user-mention">@context</a>" : "http://schema.org",
            "<a href="https://github.com/type" class="user-mention">@type</a>" : "Organization",
            "name" : "Hipster Pixel",
            "url" : "https://hipsterpixel.co",
            "sameAs" : [
              "https://twitter.com/hipsterpixel",
              "https://www.google.com/+HipsterPixel",
              "https://www.facebook.com/hipsterpixel",
              "http://instagram.com/_hipsterpixel"
            ]
        }
        </script>
    <main class="container">
```

the first two should look like this:
```
            "@context":  "http://schema.org",
            "@type" : "Organization",
```

**Comment by parkr** [comment]
@vallieres Hi! We use [html-pipeline](https://github.com/jch/html-pipeline) to convert this. Please make sure you're running the latest version (check the Releases on this repo and rubygems.org). If you're not, please upgrade and try again. If the problem persists, please file an issue on the html-pipeline repo I mentioned above and they can assist you further. 😄

**Comment by vallieres** [comment]
Sure! :) I did have the latest one, after realizing my json-ld was broken, I updated and confirmed it was still happening. I'll open a ticket there. Thanks!

**Comment by Haroenv** [comment]
I'm having this same problem, however I was writing `json-ld` in a `<pre>` tag, and not a `<script>`. Maybe it's possible to disable this extension for a specific file via the front matter?
