### ISSUE TITLE
Does not work with usernames with capital letters

### ISSUE THREAD

**Issue by benbalter** [jekyll/jekyll-mentions#32]
May need to be fixed upstream, but opening here to track.

**Comment by kivikakk** [comment]
This is fixed as of #33; I think we just need to get a release cut now so we can use this elsewhere?

**Comment by parkr** [comment]
Done! https://github.com/jekyll/jekyll-mentions/releases/tag/v1.1.3

**Comment by kivikakk** [comment]
Great, thank you! :heart:
