### ISSUE TITLE
Open link in new tab

### ISSUE THREAD

**Issue by kenold** [jekyll/jekyll-mentions#41]
Is there a way to open link in a new tab? ex: target="_blank"?

**Comment by benbalter** [comment]
Not right now. The link format is [hardcoded upstream](https://github.com/jch/html-pipeline/blob/master/lib/html/pipeline/%40mention_filter.rb#L132) in the HTML Pipeline project. If you opened an issue there to add the option, we'd be able to support it here.

**Comment by kenold** [comment]
Done! Thanks for the quick reply. https://github.com/jch/html-pipeline/issues/266
