### ISSUE TITLE
Dependency Error: activesupport due to json

### ISSUE THREAD

**Issue by swizca** [jekyll/jekyll-mentions#42]
Followed readme as written.

Result:
Dependency Error: Yikes! It looks like you don't have jekyll-mentions or one of its dependencies installed. In order to use Jekyll as currently configured, you'll need to install this gem. The full error message from Ruby is: 'Unable to activate activesupport-4.2.7, because json-2.0.2 conflicts with json (>= 1.7.7, ~> 1.7)' If you run into trouble, you can find helpful resources at http://jekyllrb.com/help/! 
jekyll 3.3.1 | Error:  jekyll-mentions

**Comment by Starefossen** [comment]
Any thoughts on this one @parkr?

**Comment by parkr** [comment]
The relevant line is `Unable to activate activesupport-4.2.7, because json-2.0.2 conflicts with json (>= 1.7.7, ~> 1.7)`

Are you using `bundle exec`? If not, then run `gem uninstall json` and select the 1.7 versions and remove them.

**Comment by Starefossen** [comment]
I could not uninstall the oldest version on my installation since it was set as default by Rubygems.

I ended up installing `activesupport` v4.2.8 which no longer has an dependency on `json` removing this issue entirely.

```
gem install activesupport 'v4.2.8'
```
