### ISSUE TITLE
Not working with username @s_name (Twitter)

### ISSUE THREAD

**Issue by 7php** [jekyll/jekyll-mentions#45]
I think I found a bug around a use-case below..

FYI:
- I'm using jekyllrb v3.5.0
- in _config.yml I've changed to using Twitter:
```
jekyll-mentions:
  base_url: https://twitter.com
```

On my blog I do a lot of mentions. And I noticed that it's not working for username like: `@s_bergmann`
Which is a valid Twitter handle, see: https://twitter.com/@s_bergmann

**Comment by DirtyF** [comment]
This bug is easily reproductible and still valid.

**Comment by 7php** [comment]
@ashmaroli thanks for fixing this.
