### ISSUE TITLE
Adding options to the HTML a tag

### ISSUE THREAD

**Issue by ianwinter** [jekyll/jekyll-mentions#48]
Is it possible to add additional tags to the `a` tag itself? I'm specifically thinking about `title` and `rel` (partly due to https://www.jitbit.com/alexblog/256-targetblank---the-most-underestimated-vulnerability-ever/).

Rather than
```
<a href="https://twitter.com/username">@username</a>
```

Be more like
```
<a href="https://twitter.com/username" title="@username" rel="noopener noreferrer">@username</a>
```

**Comment by benbalter** [comment]
This plugin simply wraps the HTML Pipeline @mention filter. The additional properties would have to be added to https://github.com/jch/html-pipeline/blob/717f6ef4f03a6e3e3d487feae2250eb58940257a/lib/html/pipeline/%40mention_filter.rb#L119-L124.

**Comment by ianwinter** [comment]
Ah OK, that makes sense. I'll head down that route. Thanks.
