### ISSUE TITLE
Encode CJK url

### ISSUE THREAD

**Issue by zYeoman** [jekyll/jekyll-mentions#52]
For example, in the TOC the URL is encoded from '#链接’ to '#%E9%93%BE%E6%8E%A5', which is not so comfortable with my javascript code.  (I can use $('#链接') but $('#%E9%93%BE%E6%8E%A5') will cause error.)

**Comment by DirtyF** [comment]
Please provide a complete use case and a link to a public repository if you think this is related to this plugin. It might be a much broader issue though.

**Comment by parkr** [comment]
Closing as stale.
