### ISSUE TITLE
Add span class for @

### ISSUE THREAD

**Issue by xplosionmind** [jekyll/jekyll-mentions#75]
The whole parsed HTML `<a>` tag has `user-mention` as a class, but it would be really nice and useful to parse a `<span>` tag which contains the @ only, so that it could be styled differently.

**Comment by ashmaroli** [comment]
How is styling a particular `<span>` different from just styling the entire `<a>` tag?

**Comment by xplosionmind** [comment]
if the `span` contains the `@` only, its color can be changed, while the color of the whole link stays the same, as default.

**Comment by ashmaroli** [comment]
Sorry, I don't see the value in having the `@` styled separately to the username.
Therefore, I'm rejecting your request.

You are free to fork the project, customize the results and use in your site.
